name: custom_time_picker_erfan
description: "A customizable time picker widget for Flutter applications"
version: 0.0.1
homepage: https://github.com/erfanalizada/custom_time_picker_erfan
repository: https://github.com/erfanalizada/custom_time_picker_erfan

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
